package seeder

import (
	"gotribe/internal/model"

	"gorm.io/gorm"
)

// ApiSeeder API种子
type ApiSeeder struct {
	*BaseSeeder
}

// NewApiSeeder 创建API种子
func NewApiSeeder() *ApiSeeder {
	return &ApiSeeder{
		BaseSeeder: NewBaseSeeder("api"),
	}
}

// Run 执行API数据种子
func (s *ApiSeeder) Run(db *gorm.DB, syncExisting bool) error {
	apis := []*model.Api{
		{
			Model:    model.Model{ID: 1},
			Method:   "POST",
			Path:     "/base/login",
			Category: "base",
			Desc:     "管理员登录",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 2},
			Method:   "POST",
			Path:     "/base/logout",
			Category: "base",
			Desc:     "管理员登出",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 3},
			Method:   "POST",
			Path:     "/base/refreshToken",
			Category: "base",
			Desc:     "刷新JWT令牌",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 108},
			Method:   "POST",
			Path:     "/base/totp/verify",
			Category: "base",
			Desc:     "TOTP 二次校验（公开，凭 step_token）",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 109},
			Method:   "GET",
			Path:     "/base/totp/status",
			Category: "base",
			Desc:     "查询当前账户 TOTP 绑定状态",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 110},
			Method:   "POST",
			Path:     "/base/totp/bind",
			Category: "base",
			Desc:     "发起 TOTP 绑定",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 111},
			Method:   "POST",
			Path:     "/base/totp/confirm",
			Category: "base",
			Desc:     "确认 TOTP 绑定",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 112},
			Method:   "DELETE",
			Path:     "/base/totp",
			Category: "base",
			Desc:     "自助解绑 TOTP",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 113},
			Method:   "POST",
			Path:     "/admin/:id/totp/reset",
			Category: "admin",
			Desc:     "超管重置他人 TOTP",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 114},
			Method:   "POST",
			Path:     "/base/totp/enroll",
			Category: "base",
			Desc:     "登录中途首次绑定 TOTP（公开，凭 step_token）",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 115},
			Method:   "POST",
			Path:     "/base/totp/enroll/confirm",
			Category: "base",
			Desc:     "确认登录中途绑定并签发 access_token",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 4},
			Method:   "GET",
			Path:     "/admin/info",
			Category: "admin",
			Desc:     "获取当前登录管理员信息",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 5},
			Method:   "GET",
			Path:     "/admin/list",
			Category: "admin",
			Desc:     "获取管理员列表",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 6},
			Method:   "PUT",
			Path:     "/admin/changePwd",
			Category: "admin",
			Desc:     "更新管理员登录密码",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 7},
			Method:   "POST",
			Path:     "/admin/create",
			Category: "admin",
			Desc:     "创建管理员",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 8},
			Method:   "PATCH",
			Path:     "/admin/update/:userID",
			Category: "admin",
			Desc:     "更新管理员",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 9},
			Method:   "DELETE",
			Path:     "/admin/delete/batch",
			Category: "admin",
			Desc:     "批量删除管理员",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 10},
			Method:   "GET",
			Path:     "/role/list",
			Category: "role",
			Desc:     "获取角色列表",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 11},
			Method:   "POST",
			Path:     "/role/create",
			Category: "role",
			Desc:     "创建角色",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 12},
			Method:   "PATCH",
			Path:     "/role/update/:roleID",
			Category: "role",
			Desc:     "更新角色",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 13},
			Method:   "GET",
			Path:     "/role/menus/get/:roleID",
			Category: "role",
			Desc:     "获取角色的权限菜单",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 14},
			Method:   "PATCH",
			Path:     "/role/menus/update/:roleID",
			Category: "role",
			Desc:     "更新角色的权限菜单",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 15},
			Method:   "GET",
			Path:     "/role/apis/get/:roleID",
			Category: "role",
			Desc:     "获取角色的权限接口",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 16},
			Method:   "PATCH",
			Path:     "/role/apis/update/:roleID",
			Category: "role",
			Desc:     "更新角色的权限接口",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 17},
			Method:   "DELETE",
			Path:     "/role/delete/batch",
			Category: "role",
			Desc:     "批量删除角色",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 18},
			Method:   "GET",
			Path:     "/menu/list",
			Category: "menu",
			Desc:     "获取菜单列表",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 19},
			Method:   "GET",
			Path:     "/menu/tree",
			Category: "menu",
			Desc:     "获取菜单树",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 20},
			Method:   "POST",
			Path:     "/menu/create",
			Category: "menu",
			Desc:     "创建菜单",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 21},
			Method:   "PATCH",
			Path:     "/menu/update/:menuID",
			Category: "menu",
			Desc:     "更新菜单",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 22},
			Method:   "DELETE",
			Path:     "/menu/delete/batch",
			Category: "menu",
			Desc:     "批量删除菜单",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 23},
			Method:   "GET",
			Path:     "/menu/access/list/:userID",
			Category: "menu",
			Desc:     "获取管理员的可访问菜单列表",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 24},
			Method:   "GET",
			Path:     "/menu/access/tree/:userID",
			Category: "menu",
			Desc:     "获取管理员的可访问菜单树",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 25},
			Method:   "GET",
			Path:     "/api/list",
			Category: "api",
			Desc:     "获取接口列表",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 26},
			Method:   "GET",
			Path:     "/api/tree",
			Category: "api",
			Desc:     "获取接口树",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 27},
			Method:   "POST",
			Path:     "/api/create",
			Category: "api",
			Desc:     "创建接口",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 28},
			Method:   "PATCH",
			Path:     "/api/update/:apiID",
			Category: "api",
			Desc:     "更新接口",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 29},
			Method:   "DELETE",
			Path:     "/api/delete/batch",
			Category: "api",
			Desc:     "批量删除接口",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 30},
			Method:   "GET",
			Path:     "/operation/list",
			Category: "log",
			Desc:     "获取操作日志列表",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 31},
			Method:   "DELETE",
			Path:     "/operation/delete/batch",
			Category: "log",
			Desc:     "批量删除操作日志",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 32},
			Method:   "GET",
			Path:     "/project/:id",
			Category: "project",
			Desc:     "获取单条项目详情",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 33},
			Method:   "GET",
			Path:     "/project",
			Category: "project",
			Desc:     "获取项目列表",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 34},
			Method:   "POST",
			Path:     "/project",
			Category: "project",
			Desc:     "创建项目",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 35},
			Method:   "PATCH",
			Path:     "/project/:id",
			Category: "project",
			Desc:     "更新项目",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 36},
			Method:   "DELETE",
			Path:     "/project",
			Category: "project",
			Desc:     "批量删除项目",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 37},
			Method:   "GET",
			Path:     "/config/:id",
			Category: "config",
			Desc:     "获取单条配置详情",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 38},
			Method:   "GET",
			Path:     "/config",
			Category: "config",
			Desc:     "获取配置列表",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 39},
			Method:   "POST",
			Path:     "/config",
			Category: "config",
			Desc:     "创建配置",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 40},
			Method:   "PATCH",
			Path:     "/config/:id",
			Category: "config",
			Desc:     "更新配置",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 41},
			Method:   "DELETE",
			Path:     "/config",
			Category: "config",
			Desc:     "批量删除配置",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 42},
			Method:   "GET",
			Path:     "/tag/:id",
			Category: "tag",
			Desc:     "获取单条标签详情",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 43},
			Method:   "GET",
			Path:     "/tag",
			Category: "tag",
			Desc:     "获取标签列表",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 44},
			Method:   "POST",
			Path:     "/tag",
			Category: "tag",
			Desc:     "创建标签",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 45},
			Method:   "PATCH",
			Path:     "/tag/:id",
			Category: "tag",
			Desc:     "更新标签",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 46},
			Method:   "DELETE",
			Path:     "/tag",
			Category: "tag",
			Desc:     "批量删除标签",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 47},
			Method:   "GET",
			Path:     "/category/:id",
			Category: "category",
			Desc:     "获取分类信息",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 48},
			Method:   "GET",
			Path:     "/category/tree",
			Category: "category",
			Desc:     "获取分类树",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 49},
			Method:   "GET",
			Path:     "/category",
			Category: "category",
			Desc:     "获取分类列表",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 50},
			Method:   "POST",
			Path:     "/category",
			Category: "category",
			Desc:     "创建分类",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 51},
			Method:   "PATCH",
			Path:     "/category/:id",
			Category: "category",
			Desc:     "更新分类",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 52},
			Method:   "DELETE",
			Path:     "/category",
			Category: "category",
			Desc:     "批量删除分类",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 53},
			Method:   "GET",
			Path:     "/post/:id",
			Category: "post",
			Desc:     "获取单条内容详情",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 54},
			Method:   "GET",
			Path:     "/post",
			Category: "post",
			Desc:     "获取内容列表",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 55},
			Method:   "POST",
			Path:     "/post",
			Category: "post",
			Desc:     "创建内容",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 56},
			Method:   "PATCH",
			Path:     "/post/:id",
			Category: "post",
			Desc:     "更新内容",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 57},
			Method:   "PUT",
			Path:     "/post/:id",
			Category: "post",
			Desc:     "发布内容",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 58},
			Method:   "DELETE",
			Path:     "/post",
			Category: "post",
			Desc:     "批量删除内容",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 59},
			Method:   "GET",
			Path:     "/user/:id",
			Category: "user",
			Desc:     "获取单个用户详情",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 60},
			Method:   "GET",
			Path:     "/user",
			Category: "user",
			Desc:     "获取用户列表",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 61},
			Method:   "GET",
			Path:     "/user/search",
			Category: "user",
			Desc:     "搜索用户列表",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 62},
			Method:   "POST",
			Path:     "/user",
			Category: "user",
			Desc:     "创建用户",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 63},
			Method:   "PATCH",
			Path:     "/user/:id",
			Category: "user",
			Desc:     "更新用户",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 64},
			Method:   "DELETE",
			Path:     "/user",
			Category: "user",
			Desc:     "批量删除用户",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 65},
			Method:   "POST",
			Path:     "/resource/upload",
			Category: "resource",
			Desc:     "上传资源",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 66},
			Method:   "GET",
			Path:     "/resource",
			Category: "resource",
			Desc:     "获取资源列表",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 67},
			Method:   "GET",
			Path:     "/resource/:id",
			Category: "resource",
			Desc:     "获取资源详情",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 68},
			Method:   "PATCH",
			Path:     "/resource/:id",
			Category: "resource",
			Desc:     "更新资源信息",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 69},
			Method:   "DELETE",
			Path:     "/resource",
			Category: "resource",
			Desc:     "删除资源",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 70},
			Method:   "POST",
			Path:     "/column",
			Category: "column",
			Desc:     "新增专栏",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 71},
			Method:   "GET",
			Path:     "/column",
			Category: "column",
			Desc:     "获取专栏列表",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 72},
			Method:   "GET",
			Path:     "/column/:id",
			Category: "column",
			Desc:     "获取专栏详情",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 73},
			Method:   "PATCH",
			Path:     "/column/:id",
			Category: "column",
			Desc:     "更新专栏信息",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 74},
			Method:   "DELETE",
			Path:     "/column",
			Category: "column",
			Desc:     "删除专栏",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 75},
			Method:   "GET",
			Path:     "/ad/scene/:id",
			Category: "ad_scene",
			Desc:     "获取单条推广场景",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 76},
			Method:   "GET",
			Path:     "/ad/scene",
			Category: "ad_scene",
			Desc:     "获取所有推广场景",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 77},
			Method:   "POST",
			Path:     "/ad/scene",
			Category: "ad_scene",
			Desc:     "创建推广场景",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 78},
			Method:   "DELETE",
			Path:     "/ad/scene",
			Category: "ad_scene",
			Desc:     "删除推广场景",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 79},
			Method:   "PATCH",
			Path:     "/ad/scene/:id",
			Category: "ad_scene",
			Desc:     "更新推广场景信息",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 80},
			Method:   "GET",
			Path:     "/ad/:id",
			Category: "ad",
			Desc:     "获取单个广告位",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 81},
			Method:   "GET",
			Path:     "/ad",
			Category: "ad",
			Desc:     "获取广告列表",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 82},
			Method:   "POST",
			Path:     "/ad",
			Category: "ad",
			Desc:     "创建广告",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 83},
			Method:   "PATCH",
			Path:     "/ad/:id",
			Category: "ad",
			Desc:     "更新广告",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 84},
			Method:   "DELETE",
			Path:     "/ad",
			Category: "ad",
			Desc:     "删除广告",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 85},
			Method:   "GET",
			Path:     "/comment",
			Category: "comment",
			Desc:     "获取评论列表",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 86},
			Method:   "PATCH",
			Path:     "/comment/:id",
			Category: "comment",
			Desc:     "审核评论",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 87},
			Method:   "GET",
			Path:     "/point",
			Category: "point",
			Desc:     "获取积分列表",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 88},
			Method:   "POST",
			Path:     "/point",
			Category: "point",
			Desc:     "后台增加积分",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 91},
			Method:   "DELETE",
			Path:     "/comment",
			Category: "comment",
			Desc:     "批量删除评论",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 92},
			Method:   "GET",
			Path:     "/point/:id",
			Category: "point",
			Desc:     "获取积分详情",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 93},
			Method:   "PATCH",
			Path:     "/point/:id",
			Category: "point",
			Desc:     "更新积分记录",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 94},
			Method:   "DELETE",
			Path:     "/point",
			Category: "point",
			Desc:     "批量删除积分",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 95},
			Method:   "DELETE",
			Path:     "/feedback",
			Category: "feedback",
			Desc:     "批量删除反馈",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 96},
			Method:   "GET",
			Path:     "/admin/detail/:id",
			Category: "admin",
			Desc:     "获取管理员详情",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 89},
			Method:   "GET",
			Path:     "/index/dashboard",
			Category: "Index",
			Desc:     "获取仪表盘全量数据",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 90},
			Method:   "POST",
			Path:     "/index/cache/clear",
			Category: "Index",
			Desc:     "清空 Redis 缓存",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 97},
			Method:   "GET",
			Path:     "/base/config",
			Category: "base",
			Desc:     "获取基础配置",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 98},
			Method:   "PATCH",
			Path:     "/system",
			Category: "system",
			Desc:     "更新系统配置",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 99},
			Method:   "GET",
			Path:     "/feedback",
			Category: "feedback",
			Desc:     "获取反馈列表",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 100},
			Method:   "GET",
			Path:     "/jobs/",
			Category: "job",
			Desc:     "获取任务列表",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 105},
			Method:   "GET",
			Path:     "/jobs",
			Category: "job",
			Desc:     "获取任务列表",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 106},
			Method:   "POST",
			Path:     "/ai/generate",
			Category: "ai",
			Desc:     "通用 AI 生成",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 107},
			Method:   "GET",
			Path:     "/config/alias/:alias",
			Category: "config",
			Desc:     "按别名获取配置",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 101},
			Method:   "GET",
			Path:     "/jobs/:name/status",
			Category: "job",
			Desc:     "获取任务状态",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 102},
			Method:   "GET",
			Path:     "/jobs/:name/history",
			Category: "job",
			Desc:     "获取任务历史",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 103},
			Method:   "POST",
			Path:     "/jobs/:name/enable",
			Category: "job",
			Desc:     "启用任务",
			Creator:  "系统",
		},
		{
			Model:    model.Model{ID: 104},
			Method:   "POST",
			Path:     "/jobs/:name/disable",
			Category: "job",
			Desc:     "禁用任务",
			Creator:  "系统",
		},
	}

	for _, api := range apis {
		if err := createOrSyncByID(db, api, api.ID, syncExisting, []string{
			"method",
			"path",
			"category",
			"desc",
			"creator",
		}); err != nil {
			return err
		}
	}

	return nil
}
