-- Phase 5: Initial schema migration (down)
-- Generated from GORM AutoMigrate on PostgreSQL

DROP TABLE IF EXISTS "user_event" CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS "third_party_accounts" CASCADE;
DROP TABLE IF EXISTS "tag" CASCADE;
DROP TABLE IF EXISTS "system_config" CASCADE;
DROP TABLE IF EXISTS "role_menus" CASCADE;
DROP TABLE IF EXISTS "role" CASCADE;
DROP TABLE IF EXISTS "resource" CASCADE;
DROP TABLE IF EXISTS "project" CASCADE;
DROP TABLE IF EXISTS "post_tag" CASCADE;
DROP TABLE IF EXISTS "post" CASCADE;
DROP TABLE IF EXISTS "point_log" CASCADE;
DROP TABLE IF EXISTS "point_deduction" CASCADE;
DROP TABLE IF EXISTS "point_available" CASCADE;
DROP TABLE IF EXISTS "operation_log" CASCADE;
DROP TABLE IF EXISTS "menu" CASCADE;
DROP TABLE IF EXISTS "feedback" CASCADE;
DROP TABLE IF EXISTS "config" CASCADE;
DROP TABLE IF EXISTS "comment" CASCADE;
DROP TABLE IF EXISTS "column" CASCADE;
DROP TABLE IF EXISTS "category" CASCADE;
DROP TABLE IF EXISTS "api" CASCADE;
DROP TABLE IF EXISTS "admin_roles" CASCADE;
DROP TABLE IF EXISTS "admin" CASCADE;
DROP TABLE IF EXISTS "ad_scene" CASCADE;
DROP TABLE IF EXISTS "ad" CASCADE;
